---
title: "Data Persistence using SQL in EPIC"
author: "John Chapman"
date: "11/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Overview for data persistence goal:
1. Select dev server
2. Install sqlite (mysql?)
3. Transfer data to sql
  + transfer Master1 
  + cip1
  + soc1
4. Alter any code?

.. Replicate master branch using sql input/output


# Select Dev Server

* WelcomeU - to separate production from dev.  But, would mean double the maintenance/upgrades. But prob better development vs production app management.
+ What needs to happen to make Welcome U the dev server?
++ R installed - check
++ Shiny installed - check
++ git installed - check
++ install ssh public key to login from ipad

# Install Sqlite or MySQL
* SQLite is probably a sufficient sql engine for the number of users we expect and to avoid the upkeep of MySQL
+ sudo su - -c "R -e \"install.packages('RSQLite', repos='http://cran.rstudio.com/')\""

# Transfer data to sql
* copied epicdb.sqlite file from Dropbox/R-Studio/EPIC-old/data

## 2019 11 11 - first run app() results:
> Listening on http://127.0.0.1:4886  
> Warning: Error in %in%: object 'school.name' not found

Need to check on school.name field, did it transfer ok?  Is it newer than the epicdb.sqlite file? Do I need to create a new epicdb.sqlite database?  
Also need to create or tables for the soc and cip